services:
  - type: web
    name: medium-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

